baseURL = "https://theias.netlify.app/"
defaultContentLanguage = "en"
languageCode = "en-us"
relativeURLs = true
theme = "theias"

staticDir = ["static"]

[params]
colorBackground = "red"
colorMainText = "#3d405b"
colorNavbar = "#fff"
colorPrimary = "#aaa"
